#!/usr/bin/sh
env_file=".env"

if [ -f "$env_file" ]
then
    export $(cat .env | xargs)
else
    echo "WARNING: Missing $env_file file."
fi

if [ -z "$NGROK_AUTHTOKEN" ]; then
    echo "WARNING: NGROK_AUTHTOKEN is not defined"
fi

nohup ngrok start --all --config ./ngrok.yml &
echo "Ngrok started. Client is accessible on https://forradia-world.ngrok-free.app"
sudo ./server/build/forradia-world
echo "Exiting Ngrok..."
pkill ngrok
